name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-only:
    runs-on: macos-13

    steps:
    - name: Select Xcode 15.2
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: |
        xcodebuild build \
          -project GithubActions.xcodeproj \
          -scheme GithubActions \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
